# Generated by Django 4.2.4 on 2023-08-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
