# Generated by Django 4.2.4 on 2023-08-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_best_seller_sub_category_bed_decor_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="image",),
    ]
