# Generated by Django 4.2.4 on 2023-09-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_category_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="title", new_name="cat_title",
        ),
    ]
