# Generated by Django 4.2.4 on 2023-09-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_title_category_cat_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sub_category", old_name="title", new_name="sub_cat_title",
        ),
    ]
