# Generated by Django 4.2.4 on 2023-09-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_title_sub_category_sub_cat_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="main_category", old_name="title", new_name="main_title",
        ),
    ]
