# Generated by Django 4.2.4 on 2023-09-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0008_rename_bed_decor_category_sub_category_carpet_tile_for_office_brands_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sub_category",
            name="carpet_rolls_brands",
            field=models.BooleanField(default=False),
        ),
    ]
