# Generated by Django 4.2.4 on 2023-09-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_sub_category_big_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="sub_category", name="big_image",),
    ]
