# Generated by Django 4.2.4 on 2023-09-13 08:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_sub_category_big_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="big_image",
            field=models.ImageField(
                default="bigcategory.jpg", upload_to=core.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="category.jpg", upload_to=core.models.user_directory_path
            ),
        ),
    ]
