# Generated by Django 4.2.4 on 2023-09-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_category_big_image_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sub_category",
            name="curtain_fabric_category",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sub_category",
            name="fabric_use_upholstery_category",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sub_category",
            name="wall_panel_category",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sub_category",
            name="window_blinds_category",
            field=models.BooleanField(default=False),
        ),
    ]
