# Generated by Django 4.2.4 on 2023-09-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_sub_category_curtain_fabric_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_category",
            name="icon_img",
            field=models.ImageField(
                default="maincategoryicon.jpg", upload_to="categoryicon"
            ),
        ),
    ]
