# Generated by Django 4.2.4 on 2023-09-15 13:01

import core.models
from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_sub_category_description_sub_category_main_page_img"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="tags",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product.jpg", upload_to=core.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345678900",
                length=22,
                max_length=50,
                prefix="sku",
                unique=True,
            ),
        ),
    ]
