# Generated by Django 4.2.4 on 2023-09-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_product_tags_product_image_alter_product_sku"),
    ]

    operations = [
        migrations.RenameField(model_name="product", old_name="sid", new_name="pid",),
    ]
