# Generated by Django 4.2.4 on 2023-09-25 07:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_sid_product_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_for_architect",
            field=models.DecimalField(
                decimal_places=2, default="1.99", max_digits=99999999999999
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_for_importers",
            field=models.DecimalField(
                decimal_places=2, default="1.99", max_digits=99999999999999
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_for_user",
            field=models.DecimalField(
                decimal_places=2, default="1.99", max_digits=99999999999999
            ),
        ),
        migrations.AddField(
            model_name="sub_category",
            name="logo_img",
            field=models.ImageField(
                default="logo.jpg", upload_to=core.models.user_directory_path
            ),
        ),
    ]
