# Generated by Django 4.2.4 on 2023-09-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_product_discount_for_architect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sub_category",
            name="maincat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.main_category",
            ),
        ),
    ]
