# Generated by Django 4.2.4 on 2023-10-02 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0021_product_category_product_main_category"),
    ]

    operations = [
        migrations.RenameModel(old_name="Sub_category", new_name="Company_name",),
    ]
