# Generated by Django 4.2.4 on 2023-10-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_rename_sub_category_company_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company_name", options={"verbose_name_plural": "Company Name"},
        ),
        migrations.RenameField(
            model_name="product", old_name="sub_category", new_name="company_name",
        ),
    ]
