# Generated by Django 4.2.4 on 2023-10-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_company_name_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="company_name", name="user",),
    ]
