# Generated by Django 4.2.4 on 2023-10-02 18:17

import core.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_company_name_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company_name",
            old_name="sub_cat_title",
            new_name="company_name_title",
        ),
        migrations.AlterField(
            model_name="company_name",
            name="sid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=22,
                max_length=30,
                prefix="Company_name",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Sub_categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ssid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=22,
                        max_length=30,
                        prefix="sub_cat",
                        unique=True,
                    ),
                ),
                (
                    "sub_cat_title",
                    models.CharField(default="Mobile & Laptop", max_length=100),
                ),
                ("meta_description", models.CharField(max_length=100)),
                ("meta_title", models.CharField(max_length=100)),
                ("meta_tag", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        default="subcategory.jpg",
                        upload_to=core.models.user_directory_path,
                    ),
                ),
                (
                    "main_page_img",
                    models.ImageField(
                        default="mainpageimg.jpg",
                        upload_to=core.models.user_directory_path,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
                (
                    "maincat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.main_category",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Company Name",},
        ),
        migrations.AddField(
            model_name="company_name",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sub_categories",
            ),
        ),
    ]
