# Generated by Django 4.2.4 on 2023-10-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rename_sub_cat_title_company_name_company_name_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sub_categories", options={"verbose_name_plural": "Sub Categories"},
        ),
    ]
