# Generated by Django 4.2.4 on 2023-10-04 07:12

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_product_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_name",
            name="sid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=22,
                max_length=50,
                prefix="Company_name",
                unique=True,
            ),
        ),
    ]
