# Generated by Django 4.2.4 on 2023-10-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_company_name_sid"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_name",
            name="hash_name_section",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
