# Generated by Django 4.2.4 on 2023-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_company_name_hash_name_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_name",
            name="hash_name_section",
            field=models.CharField(default="", editable=False, max_length=100),
        ),
    ]
