# Generated by Django 4.2.4 on 2023-10-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_company_name_hash_name_section"),
    ]

    operations = [
        migrations.RemoveField(model_name="company_name", name="hash_name_section",),
    ]
