# Generated by Django 4.2.4 on 2023-10-15 05:56

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_productvarient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvarient",
            name="pid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=22,
                max_length=30,
                prefix="sub_cat",
                unique=True,
            ),
        ),
    ]
