# Generated by Django 4.2.4 on 2023-10-15 06:51

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_delete_productvarient"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVarient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=22,
                        max_length=30,
                        prefix="sub_cat",
                        unique=True,
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        default="product.jpg", upload_to="product-images"
                    ),
                ),
                ("title", models.CharField(default="Product Varient", max_length=100)),
                ("meta_description", models.CharField(max_length=100)),
                ("meta_title", models.CharField(max_length=100)),
                ("meta_tag", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="This is the product", null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default="1.99", max_digits=99999999999999
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, default="2.99", max_digits=99999999999
                    ),
                ),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("disabled", "Disabled"),
                            ("rejected", "Rejected"),
                            ("in_review", "In Review"),
                            ("published", "Published"),
                        ],
                        default="in_review",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("black", "Black"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                            ("orange", "Orange"),
                        ],
                        default="black",
                        max_length=10,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="12345678900",
                        length=22,
                        max_length=50,
                        prefix="sku",
                        unique=True,
                    ),
                ),
                ("updated", models.DateTimeField(null=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Varient",},
        ),
    ]
