# Generated by Django 4.2.4 on 2023-10-15 08:18

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_productvarient_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="productvarient", name="images",),
        migrations.CreateModel(
            name="ProductVarientImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="productvarient.jpg",
                        upload_to=core.models.user_directory_path,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
                (
                    "product_varient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productvarient",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Varient Images",},
        ),
    ]
