# Generated by Django 4.2.4 on 2023-10-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_productvarientimages_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvarientimages",
            options={"verbose_name_plural": "Product Variant Images"},
        ),
        migrations.AlterField(
            model_name="productvarientimages",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productvarientimages",
            name="product_varient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productvarient",
            ),
            preserve_default=False,
        ),
    ]
