# Generated by Django 4.2.4 on 2023-10-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_productvarientimages_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductVarientImages",),
    ]
