# Generated by Django 4.2.4 on 2023-10-15 10:42

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_delete_productvarientimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="productvarient.jpg",
                        upload_to=core.models.user_directory_path,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productvarient",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Variant Images",},
        ),
    ]
