# Generated by Django 4.2.4 on 2023-10-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_productvariantimages_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_name",
            name="pvc_rubber_flooring_brands",
            field=models.BooleanField(default=False),
        ),
    ]
