# Generated by Django 4.2.4 on 2023-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_company_name_pvc_rubber_flooring_brands"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_name",
            name="pillow_brands",
            field=models.BooleanField(default=False),
        ),
    ]
